name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v41.0.12
        env:
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
